name: Build and Release Go Application for Multiple Architectures

on:
  push:
    branches:
      - main
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows]
        arch: [386, amd64]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o ${{ github.repository }}-${{ matrix.os }}-${{ matrix.arch }}-${{ github.ref }}
          cp stack.env.example ${{ github.repository }}-${{ matrix.os }}-${{ matrix.arch }}-${{ github.ref }}/.env.example
          cp README.md ${{ github.repository }}-${{ matrix.os }}-${{ matrix.arch }}-${{ github.ref }}/
          ls

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.repository }}-${{ matrix.os }}-${{ matrix.arch }}-${{ github.ref }}
          path: ${{ github.repository }}-${{ matrix.os }}-${{ matrix.arch }}-${{ github.ref }}